/*
 * Copyright (C) 2015 thirdy
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package net.thirdy.blackmarket.util;

/**
 * @author thirdy
 *
 */
public class Uniques {
	
	public static String[] names = new String[] {
			"Abberath's Horn",
			"Abyssus",
			"Acton's Nightmare",
			"Aegis Aurora",
			"Agnerod East",
			"Agnerod North",
			"Agnerod South",
			"Alberon's Warpath",
			"Al Dhih",
			"Alpha's Howl",
			"Ambu's Charge",
			"Anatomical Knowledge",
			"Andvarius",
			"Apep's Rage",
			"Apparitions",
			"Araku Tiki",
			"Army of Bones",
			"Asenath's Gentle Touch",
			"Asenath's Mark",
			"Ashrend",
			"Asphyxia's Wrath",
			"Assassin's Haste",
			"Astramentis",
			"Atziri's Acuity",
			"Atziri's Disfavour",
			"Atziri's Foible",
			"Atziri's Mirror",
			"Atziri's Promise",
			"Atziri's Splendour",
			"Atziri's Step",
			"Aurseize",
			"Aurumvorax",
			"Auxium",
			"Bated Breath",
			"Belly of the Beast",
			"Belt of the Deceiver",
			"Berek's Grip",
			"Berek's Pass",
			"Bino's Kitchen Knife",
			"Blackgleam",
			"Blackheart",
			"Black Sun Crest",
			"Bloodboil",
			"Bloodgrip",
			"Blood of the Karui",
			"Bloodplay",
			"Bloodseeker",
			"Bones of Ullr",
			"Bramblejack",
			"Brawn",
			"Brightbeak",
			"Brinerot Flag",
			"Brinerot Mark",
			"Brinerot Whalers",
			"Briskwrap",
			"Broken Faith",
			"Bronn's Lithe",
			"Brute Force Solution",
			"Brutus' Lead Sprinkler",
			"Callinellus Malleus",
			"Call of the Brotherhood",
			"Cameria's Maul",
			"Carcass Jack",
			"Careful Planning",
			"Carnage Heart",
			"Chalice of Horrors",
			"Chernobog's Pillar",
			"Cherrubim's Maleficence",
			"Chin Sol",
			"Chitus' Apex",
			"Chober Chaber",
			"Clear Mind",
			"Cloak of Defiance",
			"Cloak of Flame",
			"Cold Steel",
			"Conqueror's Efficiency",
			"Conqueror's Longevity",
			"Conqueror's Potency",
			"Craghead",
			"Crest of Perandus",
			"Crown of Eyes",
			"Crown of the Pale King",
			"Crown of Thorns",
			"Cybil's Paw",
			"Daresso's Courage",
			"Daresso's Defiance",
			"Daresso's Salute",
			"Darkray Vectors",
			"Darkscorn",
			"Death's Hand",
			"Death's Harp",
			"Death's Oath",
			"Death and Taxes",
			"Death Rush",
			"Deerstalker",
			"Deidbell",
			"Demigod's Beacon",
			"Demigod's Eye",
			"Devoto's Devotion",
			"Divinarius",
			"Divination Distillate",
			"Doedre's Damning",
			"Doedre's Elixir",
			"Doedre's Scorn",
			"Doedre's Tenure",
			"Doomfletch",
			"Doomsower",
			"Doon Cuebiyari",
			"Doryani's Catalyst",
			"Doryani's Fist",
			"Doryani's Invitation",
			"Dreadarc",
			"Dreamfeather",
			"Dream Fragments",
			"Drillneck",
			"Dusktoe",
			"Dyadian Dawn",
			"Dyadus",
			"Dying Breath",
			"Edge of Madness",
			"Efficient Training",
			"Eldritch Knowledge",
			"Emberwake",
			"Empire's Grasp",
			"Energised Armour",
			"Energy From Within",
			"Ephemeral Edge",
			"Essentia Sanguis",
			"Eye of Chayula",
			"Ezomyte Peak",
			"Facebreaker",
			"Fairgraves' Tricorne",
			"Fencoil",
			"Fertile Mind",
			"Fidelitas' Spike",
			"Fireborn",
			"Flesh-Eater",
			"Flesh and Spirit",
			"Fluid Motion",
			"Forbidden Taste",
			"Fortified Legion",
			"Foxshade",
			"Fragile Bloom",
			"Gang's Momentum",
			"Geofri's Baptism",
			"Geofri's Crest",
			"Gifts from Above",
			"Goldrim",
			"Goldwyrm",
			"Gorebreaker",
			"Goredrill",
			"Great Old One's Ward",
			"Greed's Embrace",
			"Hall of Grandmasters",
			"Healthy Mind",
			"Heartbound Loop",
			"Heartbreaker",
			"Heatshiver",
			"Hegemony's Era",
			"Hidden Potential",
			"Honourhome",
			"Hotfooted",
			"Hrimnor's Hymn",
			"Hrimnor's Resolve",
			"Hrimsorrow",
			"Hyaon's Fury",
			"Hyrri's Bite",
			"Hyrri's Ire",
			"Icetomb",
			"Ichimonji",
			"Immortal Flesh",
			"Incandescent Heart",
			"Inertia",
			"Infernal Mantle",
			"Infractem",
			"Inspired Learning",
			"Intuitive Leap",
			"Jack, the Axe",
			"Jaws of Agony",
			"Kaltenhalt",
			"Kaom's Heart",
			"Kaom's Primacy",
			"Kaom's Roots",
			"Kaom's Sign",
			"Karui Ward",
			"Kikazaru",
			"Kingmaker",
			"Kingsguard",
			"Kongor's Undying Rage",
			"Lakishu's Blade",
			"Last Resort",
			"Lavianga's Spirit",
			"Lavianga's Wisdom",
			"Leer Cast",
			"Le Heup of All",
			"Lifesprig",
			"Lightbane Raiment",
			"Lightning Coil",
			"Limbsplit",
			"Lion's Roar",
			"Lioneye's Fall",
			"Lioneye's Glare",
			"Lioneye's Paws",
			"Lioneye's Remorse",
			"Lioneye's Vision",
			"Lochtonial Caress",
			"Lori's Lantern",
			"Maelstrom of Chaos",
			"Malachai's Artifice",
			"Malachai's Simula",
			"Malicious Intent",
			"Maligaro's Lens",
			"Maligaro's Restraint",
			"Maligaro's Virtuosity",
			"Maloney's Nightfall",
			"Mantra of Flames",
			"Mao Kun",
			"Mark of the Doubting Knight",
			"Marohi Erqi",
			"Martial Artistry",
			"Marylene's Fallacy",
			"Matua Tupuna",
			"Meginord's Girdle",
			"Meginord's Vise",
			"Midnight Bargain",
			"Mightflay",
			"Might in All Forms",
			"Mindspiral",
			"Ming's Heart",
			"Mjolner",
			"Mokou's Embrace",
			"Mon'tregul's Grasp",
			"Moonbender's Wing",
			"Moonsorrow",
			"Mortem Morsu",
			"Mutewind Pennant",
			"Mutewind Seal",
			"Mutewind Whispersteps",
			"Ngamahu's Sign",
			"Nomic's Storm",
			"Null's Inclination",
			"Nycta's Lantern",
			"Oba's Cursed Trove",
			"Olmec's Sanctum",
			"Ondar's Clasp",
			"Ornament of the East",
			"Oro's Sacrifice",
			"Perandus Blazon",
			"Perandus Signet",
			"Pillar of the Caged God",
			"Piscator's Vigil",
			"Pledge of Hands",
			"Poacher's Aim",
			"Poorjoy's Asylum",
			"Prismatic Eclipse",
			"Prism Guardian",
			"Prismweave",
			"Pugilist",
			"Pyre",
			"Quecholli",
			"Queen's Decree",
			"Queen of the Forest",
			"Quill Rain",
			"Rainbowstride",
			"Rain of Splinters",
			"Rashkaldor's Patience",
			"Rat's Nest",
			"Rathpith Globe",
			"Realmshaper",
			"Reaper's Pursuit",
			"Rearguard",
			"Rebuke of the Vaal",
			"Redbeak",
			"Redblade Band",
			"Redblade Banner",
			"Redblade Tramplers",
			"Relentless Fury",
			"Reverberation Rod",
			"Rigvald's Charge",
			"Rime Gaze",
			"Rise of the Phoenix",
			"Romira's Banquet",
			"Rumi's Concoction",
			"Sadima's Touch",
			"Saffell's Frame",
			"Scold's Bridle",
			"Sentari's Answer",
			"Shackles of the Wretched",
			"Shadows and Dust",
			"Shaper's Seed",
			"Shavronne's Pace",
			"Shavronne's Revelation",
			"Shavronne's Wrappings",
			"Shiversting",
			"Sibyl's Lament",
			"Sidhebreath",
			"Silverbranch",
			"Sin Trek",
			"Sire of Shards",
			"Skullhead",
			"Slitherpinch",
			"Snakebite",
			"Solaris Lorica",
			"Soul Mantle",
			"Soul Strike",
			"Soul Taker",
			"Southbound",
			"Spire of Stone",
			"Springleaf",
			"Starkonja's Head",
			"Static Electricity",
			"Steppan Eard",
			"Stone of Lazhwar",
			"Storm Cloud",
			"Sunblast",
			"Sundance",
			"Surgebinders",
			"Survival Instincts",
			"Survival Secrets",
			"Survival Skills",
			"Tabula Rasa",
			"Talisman of the Victor",
			"Taryn's Shiver",
			"Tasalio's Sign",
			"Taste of Hate",
			"Tear of Purity",
			"Terminus Est",
			"The Anvil",
			"The Blood Dance",
			"The Blood Reaper",
			"The Blood Thorn",
			"The Bringer of Rain",
			"The Broken Crown",
			"The Consuming Dark",
			"The Covenant",
			"The Coward's Trial",
			"The Dark Seer",
			"The Deep One's Hide",
			"The Goddess Bound",
			"The Goddess Scorned",
			"The Gull",
			"The Ignomon",
			"The Magnate",
			"The Pariah",
			"The Peregrine",
			"The Princess",
			"The Rat Cage",
			"The Restless Ward",
			"The Screaming Eagle",
			"The Searing Touch",
			"The Stormheart",
			"The Supreme Truth",
			"The Three Dragons",
			"The Vertex",
			"The Whispering Ice",
			"Thief's Torment",
			"Thousand Ribbons",
			"Thousand Teeth Temu",
			"Thunderfist",
			"Timeclasp",
			"Titucius' Span",
			"Tremor Rod",
			"Twyzel",
			"Ungil's Gauche",
			"Ungil's Harmony",
			"Vaal Caress",
			"Vaults of Atziri",
			"Veil of the Night",
			"Ventor's Gamble",
			"Victario's Acuity",
			"Victario's Flight",
			"Victario's Influence",
			"Vis Mortis",
			"Void Battery",
			"Voidbringer",
			"Voideye",
			"Voidhome",
			"Voll's Devotion",
			"Voll's Protector",
			"Voltaxic Rift",
			"Wake of Destruction",
			"Wanderlust",
			"Warlord's Reach",
			"Warped Timepiece",
			"Whakawairua Tuahu",
			"Wheel of the Stormsail",
			"Wideswing",
			"Wildslash",
			"Windripper",
			"Windscream",
			"Wings of Entropy",
			"Wondertrap",
			"Wurm's Molt",
			"Zahndethus' Cassock"
	};

}
